### ISSUE TITLE
A problem occurred while executing using PostSPH

### ISSUE THREAD

**Issue by zhu-hui-ling** [AhmedSalih3d/PostSPH.jl#23]
When I install it and want to simulate exporting a case's BI4 file, the following problem occurs when I execute using PostSPH.
1.ERROR: LoadError: LoadError: ArgumentError: Package PostSPH does not have WriteVTK in its dependencies:
- If you have PostSPH checked out for development and have
  added WriteVTK as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
- Otherwise you may need to report an issue with PostSPH
2.ERROR: Failed to precompile PostSPH [3add7fd0-679a-11e9-0c14-5b1cacad3044] to C:\Users\61773\.julia\compiled\v1.1\PostSPH\51Lgh.ji.
What should I do to solve this problem?

**Comment by AhmedSalih3d** [comment]
Hi Zhu!

I will look into this. For some reason Github did not send me any message.

**Comment by AhmedSalih3d** [comment]
Hi @zhu-hui-ling 

I have cleaned up the master repo and fixed the issue. The issue was some missing dependencies. I have tested on version 1.5 of Julia - I think it should work fine on other versions too.

In Julia please do, "using Pkg", "Pkg.rm("PostSPH")" and then install PostSPH as in the tutorial.

I added also a very short example file in the folder example. It shows how to import bi4 data and how to save it to a vtp file. 
**Reading vtk is not possible right now, only in older version of repo**
Please reopen this issue if your issue persists and open a new issue for different problems.
